import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import Chafa from "chafa-wasm";

import {
  PI_PIXEL_ALPHA_THRESHOLD,
  PI_PIXEL_PALETTE,
  renderPiPixelFrame,
} from "./pi-pixel-renderer.mjs";
import {
  STARTUP_BACKGROUND_MAX_CHROMA,
  STARTUP_BACKGROUND_MIN_LUMINANCE,
  encodeRgbaPng,
  normalizeStartupSheet,
} from "./startup-icon-normalizer.mjs";

const FRAME_COUNT = 12;
const MINT_IDLE_FRAME_INDEX = 6;
const STARTUP_SOURCE_URL = new URL("../assets/source/pi-icon-pixel-contact-sheet.png", import.meta.url);
const STARTUP_FRAME_DIRECTORY_URL = new URL("../assets/frames/startup-icon/", import.meta.url);
const OUTPUT_URL = new URL("../generated/pi-network-art.ts", import.meta.url);

const frameUrls = (directory) => Object.freeze(
  Array.from({ length: FRAME_COUNT }, (_, index) =>
    new URL(`../assets/frames/${directory}/frame-${index.toString().padStart(2, "0")}.png`, import.meta.url),
  ),
);
const STARTUP_FRAME_URLS = frameUrls("startup-icon");
const MINT_FRAME_URLS = frameUrls("minting");
const SEQUENCES = Object.freeze([
  Object.freeze({
    name: "startupIcon",
    exportName: "STARTUP_ICON_ART",
    variants: Object.freeze([
      Object.freeze({ name: "full", columns: 30, rows: 15 }),
      Object.freeze({ name: "compact", columns: 18, rows: 9 }),
    ]),
  }),
  Object.freeze({
    name: "mintingPane",
    exportName: "MINTING_PANE_ART",
    variants: Object.freeze([
      Object.freeze({ name: "wide", columns: 28, rows: 14 }),
      Object.freeze({ name: "compact", columns: 18, rows: 9 }),
    ]),
  }),
]);

function toExactArrayBuffer(buffer) {
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
}

function declarationName(sequence, variant) {
  return `${sequence.name.replace(/([A-Z])/g, "_$1").toUpperCase()}_${variant.name.toUpperCase()}_FRAMES`;
}

function formatGeneratedModule(sourceHash, rendered) {
  const frameDeclarations = SEQUENCES.flatMap((sequence) =>
    sequence.variants.map((variant) => {
      const name = declarationName(sequence, variant);
      return `const ${name} = Object.freeze(${JSON.stringify(rendered[sequence.name][variant.name].frames, null, 2)});`;
    }),
  ).join("\n\n");

  const exports = SEQUENCES.map((sequence) => {
    const variantDeclarations = sequence.variants.map((variant) => {
      const name = declarationName(sequence, variant);
      const derived = sequence.name === "startupIcon"
        ? `    final: ${name}[${name}.length - 1]!,\n`
        : `    idle: ${name}[${MINT_IDLE_FRAME_INDEX}]!,\n    working: Object.freeze(${name}.slice(0, 8)),\n    completion: Object.freeze(${name}.slice(8)),\n`;
      return `  ${variant.name}: Object.freeze({\n    columns: ${variant.columns},\n    rows: ${variant.rows},\n    frames: ${name},\n${derived}  })`;
    }).join(",\n");
    return `export const ${sequence.exportName} = Object.freeze({\n${variantDeclarations},\n});`;
  }).join("\n\n");

  const palette = PI_PIXEL_PALETTE
    .map(({ rgb }) => `#${rgb.map((component) => component.toString(16).padStart(2, "0")).join("")}`)
    .join(", ");
  return `// Generated by scripts/generate-art.mjs from the startup-icon and minting sources.\n// Combined source SHA-256: ${sourceHash}\n// Direct half-block renderer alpha threshold: ${PI_PIXEL_ALPHA_THRESHOLD}/255. Palette: ${palette}.\n// Startup checker flood: edge-connected chroma <= ${STARTUP_BACKGROUND_MAX_CHROMA}, Rec. 709 luminance >= ${STARTUP_BACKGROUND_MIN_LUMINANCE}.\n\n${frameDeclarations}\n\n${exports}\n\n// Compatibility aliases share the same frozen startup object without duplicating frame data.\nexport const PI_COIN_ART = STARTUP_ICON_ART;\nexport const REWARD_BURST_ART = STARTUP_ICON_ART;\n`;
}

async function decode(chafaDecodeImage, source) {
  return chafaDecodeImage(toExactArrayBuffer(source));
}

async function normalizeStartupFrames(chafaDecodeImage, source) {
  const sheet = await decode(chafaDecodeImage, source);
  const frames = normalizeStartupSheet(sheet);
  await mkdir(STARTUP_FRAME_DIRECTORY_URL, { recursive: true });
  await Promise.all(frames.map((frame, index) => writeFile(STARTUP_FRAME_URLS[index], encodeRgbaPng(frame))));
  return frames;
}

function renderSequence(sequence, images) {
  return Object.fromEntries(sequence.variants.map((variant) => [
    variant.name,
    {
      frames: images.map((image) => {
        const frame = renderPiPixelFrame(image, variant.columns, variant.rows * 2);
        if (frame.length !== variant.rows) {
          throw new Error(`Unexpected row count for ${sequence.name} ${variant.name}`);
        }
        return frame;
      }),
    },
  ]));
}

async function main() {
  const sourceHash = createHash("sha256");
  const startupSource = await readFile(STARTUP_SOURCE_URL);
  sourceHash.update("startupIcon:contact-sheet");
  sourceHash.update(startupSource);

  const mintSources = await Promise.all(MINT_FRAME_URLS.map((url) => readFile(url)));
  for (const [index, source] of mintSources.entries()) {
    sourceHash.update(`mintingPane:${index.toString().padStart(2, "0")}`);
    sourceHash.update(source);
  }

  const chafa = await Chafa();
  const decodeImage = promisify(chafa.decodeImage);
  const startupImages = await normalizeStartupFrames(decodeImage, startupSource);
  const mintImages = await Promise.all(mintSources.map((source) => decode(decodeImage, source)));
  for (const image of mintImages) {
    if (image.width !== 28 || image.height !== 28) {
      throw new Error(`Mint source must be exactly 28×28 RGBA; received ${image.width}×${image.height}`);
    }
  }

  const rendered = {
    startupIcon: renderSequence(SEQUENCES[0], startupImages),
    mintingPane: renderSequence(SEQUENCES[1], mintImages),
  };
  await writeFile(OUTPUT_URL, formatGeneratedModule(sourceHash.digest("hex"), rendered), "utf8");
  console.log(`Generated ${fileURLToPath(OUTPUT_URL)} from two ${FRAME_COUNT}-frame sequences`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
